
import React from 'react';
import { PlaceholderTool } from './PlaceholderTool';

interface AIDetectorToolProps {
  onSendToChat: (message: string) => void;
}

export const AIDetectorTool: React.FC<AIDetectorToolProps> = ({ onSendToChat }) => {
  return (
    <PlaceholderTool
      toolName="AI Detector"
      description="Determine if text was likely generated by AI."
      onSendToChat={onSendToChat}
    />
  );
};
